name: (Internal) iOS Production Release

on:
  repository_dispatch:
    types: [deploy]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  branch: "master"
  java_version: "12.x"
  ruby_path: "./vendor/bundle"
  ruby_version: "2.7.2"

jobs:
  deploy_ios:
    name: Deploy beta build to TestFlight
    runs-on: macos-latest
    steps:
      # Set up
      - uses: actions/checkout@v1
        with:
          ref: ${{ env.branch }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Initialize environment variables from FVM config
        uses: kuhnroyal/flutter-fvm-config-action@v1
      - name: Cache ruby dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.ruby_path }}
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-install-cache-${{ env.FLUTTER_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # Flutter actions
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter packages pub run build_runner build --enable-experiment=records,patterns,sealed-class
      - run: flutter build ios --flavor prod --dart-define=env.mode=prod --release --no-codesign

      # Fastlane deploy
      - name: Deploy iOS Beta to TestFlight via Fastlane
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: beta
          subdirectory: ios
          bundle-install-path: ${{ env.ruby_path }}
        env:
          APP_STORE_CONNECT_TEAM_ID: ${{ secrets.APP_STORE_CONNECT_TEAM_ID }}
          DEVELOPER_APP_ID: ${{ secrets.DEVELOPER_APP_ID }}
          DEVELOPER_APP_IDENTIFIER: ${{ secrets.DEVELOPER_APP_IDENTIFIER }}
          DEVELOPER_PORTAL_TEAM_ID: ${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}
          FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
          PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
